stages:
- build
- test

variables:
  IMAGE_NAME_DEV: $CI_REGISTRY/jukebox/music-server/dev:$CI_COMMIT_REF_SLUG
  IMAGE_NAME_PRO: $CI_REGISTRY/jukebox/music-server/pro:$CI_COMMIT_REF_SLUG

images:
  stage: build
  script:
    - docker build --pull -t $IMAGE_NAME_DEV -f Dockerfile.dev .
    - docker build --pull -t $IMAGE_NAME_PRO .

nginx_syntax:
  stage: test
  script:
    - docker run $IMAGE_NAME_PRO nginx -t
    - docker run $IMAGE_NAME_DEV nginx -t
